/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2022-03-02 03:39:08 
*/
import SaveContext from "../SaveContext";

export interface Igex3core {
    save: SaveContext;
}
