/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2022-03-02 03:39:08 
*/
import { ISaveContext } from "./ISaveContext";

export interface Igex3core {
    save: ISaveContext;
}
