/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2022-03-02 03:43:11 
*/

import { number_ref } from "modloader64_api/Sylvain/ImGui";

export interface ISaveContext {
    remote_count: number;
    fly_coins: number;
    paw_coins: number;
    bonus_coins: number;
    life_counter: number;
    health_counter: number;
    totally_scrooged: number;
    totally_scrooged_bonus_coins: number;
    totally_scrooged_paw_coins: number;
    clueless_in_seattle: number;
    clueless_in_seattle_bonus_coins: number;
    clueless_in_seattle_paw_coins: number;
    holy_moses: number;
    holy_moses_bonus_coins: number;
    holy_moses_paw_coins: number;
    war_is_heck: number;
    war_is_heck_bonus_coins: number;
    war_is_heck_paw_coins: number;
    the_oregon_trail: number;
    the_oregon_trail_bonus_coins: number;
    the_oregon_trail_paw_coins: number;
    cutcheese_island: number;
    cutcheese_island_bonus_coins: number;
    cutcheese_island_paw_coins: number;
    et_ty_gecko: number;
    et_ty_gecko_bonus_coins: number;
    et_ty_gecko_paw_coins: number;
    beanStalker: number;
    beanStalker_bonus_coins: number;
    beanStalker_paw_coins: number;
    when_sushi_goes_bad: number;
    when_sushi_goes_bad_bonus_coins: number;
    when_sushi_goes_bad_paw_coins: number;
    my_three_goons: number;
    my_three_goons_bonus_coins: number;
    my_three_goons_paw_coins: number;
    super_zeros: number;
    super_zeros_bonus_coins: number;
    super_zeros_paw_coins: number;
    fly_tv_remotes: number;
    mission_control: number;
    mission_control_bonus_coins: number;
    mission_control_paw_coins: number;
    lake_flaccid: number;
    lake_flaccid_bonus_coins: number;
    lake_flaccid_paw_coins: number;
    slappy_valley: number;
    slappy_valley_bonus_coins: number;
    slappy_valley_paw_coins: number;
    funky_town: number;
    funky_town_bonus_coins: number;
    funky_town_paw_coins: number;
    marsupial_madness: number;
    gextreme_sports: number;
    war_and_pieces: number;
    true_gifts: number;
    what_a_crock: number;
    secret_levels: number;
    boss_battles: number;
    doors: number;
}
